os:
  - linux

language: php

php:
  - '7.2'
  
before_script:
  - composer self-update
  - composer install --no-interaction
  - nvm install 7.7.1
  - npm install npm@latest -g
  - npm install
  
script:
  - vendor/bin/phpunit --coverage-text
  - npm run travis-build