os:
  - linux

language: php

php:
  - '7.2'

services:
  - postgresql
  
before_script:
  - mv travis.env .env
  - psql -c 'create database yaktest;' -U postgres
  - composer self-update
  - composer install --no-interaction
  
script:
  - vendor/bin/phpunit --coverage-text